platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "8" }

  type: docker-image
  source: {repository: busybox}

inputs:
- name: src-voice

run:
  path: ./build.sh
